version: "3.8"

services:
  antink-server:
    build:
      context: .
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined
    volumes:
      - ./it24_host:/home/antink
      - antink_mount:/mnt/antink
      - ./antink-logs:/var/log

  antink-logger:
    image: ubuntu:22.04
    volumes:
      - ./antink-logs:/var/log
    command: tail -f /var/log/it24.log

volumes:
  antink_mount:
